//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.27 at 06:33:24 PM IST 
//


package it.geosolutions.geostore.soap.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExceptionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExceptionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="code" type="{http://wse.vlaanderen.be/generic/Fault/common/DataTypes/v100}CodeType"/&gt;
 *         &lt;element name="desc" type="{http://wse.vlaanderen.be/generic/Fault/common/DataTypes/v100}DescriptionType" minOccurs="0"/&gt;
 *         &lt;element name="shortDesc" type="{http://wse.vlaanderen.be/generic/Fault/common/DataTypes/v100}ShortDescriptionType"/&gt;
 *         &lt;element name="category" type="{http://wse.vlaanderen.be/generic/Fault/common/DataTypes/v100}CategoryType" minOccurs="0"/&gt;
 *         &lt;element name="type" type="{http://wse.vlaanderen.be/generic/Fault/common/DataTypes/v100}FaultTypeType"/&gt;
 *         &lt;element name="severity" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="H"/&gt;
 *               &lt;enumeration value="M"/&gt;
 *               &lt;enumeration value="L"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="stackTrace" type="{http://wse.vlaanderen.be/generic/Fault/common/DataTypes/v100}StackTraceType" minOccurs="0"/&gt;
 *         &lt;element name="debugData" type="{http://wse.vlaanderen.be/generic/Fault/common/DataTypes/v100}DebugDataType" minOccurs="0"/&gt;
 *         &lt;element name="inputData" type="{http://wse.vlaanderen.be/generic/Fault/common/DataTypes/v100}InputDataType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExceptionType", namespace = "http://wse.vlaanderen.be/generic/Fault/common/DataTypes/v100", propOrder = {
    "code",
    "desc",
    "shortDesc",
    "category",
    "type",
    "severity",
    "stackTrace",
    "debugData",
    "inputData"
})
public class ExceptionType {

    @XmlElement(required = true)
    protected String code;
    protected String desc;
    @XmlElement(required = true)
    protected String shortDesc;
    protected String category;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected FaultTypeType type;
    protected String severity;
    protected String stackTrace;
    protected String debugData;
    protected String inputData;

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesc() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesc(String value) {
        this.desc = value;
    }

    /**
     * Gets the value of the shortDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortDesc() {
        return shortDesc;
    }

    /**
     * Sets the value of the shortDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortDesc(String value) {
        this.shortDesc = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link FaultTypeType }
     *     
     */
    public FaultTypeType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link FaultTypeType }
     *     
     */
    public void setType(FaultTypeType value) {
        this.type = value;
    }

    /**
     * Gets the value of the severity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeverity() {
        return severity;
    }

    /**
     * Sets the value of the severity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeverity(String value) {
        this.severity = value;
    }

    /**
     * Gets the value of the stackTrace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStackTrace() {
        return stackTrace;
    }

    /**
     * Sets the value of the stackTrace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStackTrace(String value) {
        this.stackTrace = value;
    }

    /**
     * Gets the value of the debugData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDebugData() {
        return debugData;
    }

    /**
     * Sets the value of the debugData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDebugData(String value) {
        this.debugData = value;
    }

    /**
     * Gets the value of the inputData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputData() {
        return inputData;
    }

    /**
     * Sets the value of the inputData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputData(String value) {
        this.inputData = value;
    }

}
