//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.27 at 06:33:24 PM IST 
//


package it.geosolutions.geostore.soap.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.geosolutions.geostore.soap.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Fault_QNAME = new QName("http://wse.vlaanderen.be/generic/Fault/common/DataTypes/v100", "Fault");
    private final static QName _WhereQueryList_QNAME = new QName("http://wse.vlaanderen.be/BeschikbareEntitlementArtefactService/common/DataTypes/v100", "WhereQueryList");
    private final static QName _SelectAttributeList_QNAME = new QName("http://wse.vlaanderen.be/BeschikbareEntitlementArtefactService/common/DataTypes/v100", "SelectAttributeList");
    private final static QName _QueryResult_QNAME = new QName("http://wse.vlaanderen.be/BeschikbareEntitlementArtefactService/common/DataTypes/v100", "QueryResult");
    private final static QName _QuerySingleFilterBeschikbareEntitlementFault_QNAME = new QName("http://wse.vlaanderen.be/BeschikbareEntitlementArtefactService/common/DataTypes/v100", "QuerySingleFilterBeschikbareEntitlementFault");
    private final static QName _QueryResultSet_QNAME = new QName("http://wse.vlaanderen.be/BeschikbareEntitlementArtefactService/common/DataTypes/v100", "QueryResultSet");
    private final static QName _ResultRow_QNAME = new QName("http://wse.vlaanderen.be/BeschikbareEntitlementArtefactService/common/DataTypes/v100", "ResultRow");
    private final static QName _Artefact_QNAME = new QName("http://wse.vlaanderen.be/BeschikbareEntitlementArtefactService/common/DataTypes/v100", "Artefact");
    private final static QName _SingleWhereFilterQuery_QNAME = new QName("http://wse.vlaanderen.be/BeschikbareEntitlementArtefactService/common/DataTypes/v100", "SingleWhereFilterQuery");
    private final static QName _WhereQuery_QNAME = new QName("http://wse.vlaanderen.be/BeschikbareEntitlementArtefactService/common/DataTypes/v100", "WhereQuery");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.geosolutions.geostore.soap.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FaultType }
     * 
     */
    public FaultType createFaultType() {
        return new FaultType();
    }

    /**
     * Create an instance of {@link ExceptionType }
     * 
     */
    public ExceptionType createExceptionType() {
        return new ExceptionType();
    }

    /**
     * Create an instance of {@link QuerySingleFilterBeschikbareEntitlementRequest }
     * 
     */
    public QuerySingleFilterBeschikbareEntitlementRequest createQuerySingleFilterBeschikbareEntitlementRequest() {
        return new QuerySingleFilterBeschikbareEntitlementRequest();
    }

    /**
     * Create an instance of {@link WhereQueryListType }
     * 
     */
    public WhereQueryListType createWhereQueryListType() {
        return new WhereQueryListType();
    }

    /**
     * Create an instance of {@link SelectAttributeListType }
     * 
     */
    public SelectAttributeListType createSelectAttributeListType() {
        return new SelectAttributeListType();
    }

    /**
     * Create an instance of {@link QuerySingleFilterBeschikbareEntitlementStringResponse }
     * 
     */
    public QuerySingleFilterBeschikbareEntitlementStringResponse createQuerySingleFilterBeschikbareEntitlementStringResponse() {
        return new QuerySingleFilterBeschikbareEntitlementStringResponse();
    }

    /**
     * Create an instance of {@link QueryResultType }
     * 
     */
    public QueryResultType createQueryResultType() {
        return new QueryResultType();
    }

    /**
     * Create an instance of {@link QueryResultSetType }
     * 
     */
    public QueryResultSetType createQueryResultSetType() {
        return new QueryResultSetType();
    }

    /**
     * Create an instance of {@link ResultRowType }
     * 
     */
    public ResultRowType createResultRowType() {
        return new ResultRowType();
    }

    /**
     * Create an instance of {@link ResultColumnType }
     * 
     */
    public ResultColumnType createResultColumnType() {
        return new ResultColumnType();
    }

    /**
     * Create an instance of {@link WhereFilterType }
     * 
     */
    public WhereFilterType createWhereFilterType() {
        return new WhereFilterType();
    }

    /**
     * Create an instance of {@link WhereQueryType }
     * 
     */
    public WhereQueryType createWhereQueryType() {
        return new WhereQueryType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://wse.vlaanderen.be/generic/Fault/common/DataTypes/v100", name = "Fault")
    public JAXBElement<FaultType> createFault(FaultType value) {
        return new JAXBElement<FaultType>(_Fault_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WhereQueryListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://wse.vlaanderen.be/BeschikbareEntitlementArtefactService/common/DataTypes/v100", name = "WhereQueryList")
    public JAXBElement<WhereQueryListType> createWhereQueryList(WhereQueryListType value) {
        return new JAXBElement<WhereQueryListType>(_WhereQueryList_QNAME, WhereQueryListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SelectAttributeListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://wse.vlaanderen.be/BeschikbareEntitlementArtefactService/common/DataTypes/v100", name = "SelectAttributeList")
    public JAXBElement<SelectAttributeListType> createSelectAttributeList(SelectAttributeListType value) {
        return new JAXBElement<SelectAttributeListType>(_SelectAttributeList_QNAME, SelectAttributeListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryResultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://wse.vlaanderen.be/BeschikbareEntitlementArtefactService/common/DataTypes/v100", name = "QueryResult")
    public JAXBElement<QueryResultType> createQueryResult(QueryResultType value) {
        return new JAXBElement<QueryResultType>(_QueryResult_QNAME, QueryResultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://wse.vlaanderen.be/BeschikbareEntitlementArtefactService/common/DataTypes/v100", name = "QuerySingleFilterBeschikbareEntitlementFault")
    public JAXBElement<FaultType> createQuerySingleFilterBeschikbareEntitlementFault(FaultType value) {
        return new JAXBElement<FaultType>(_QuerySingleFilterBeschikbareEntitlementFault_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryResultSetType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://wse.vlaanderen.be/BeschikbareEntitlementArtefactService/common/DataTypes/v100", name = "QueryResultSet")
    public JAXBElement<QueryResultSetType> createQueryResultSet(QueryResultSetType value) {
        return new JAXBElement<QueryResultSetType>(_QueryResultSet_QNAME, QueryResultSetType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResultRowType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://wse.vlaanderen.be/BeschikbareEntitlementArtefactService/common/DataTypes/v100", name = "ResultRow")
    public JAXBElement<ResultRowType> createResultRow(ResultRowType value) {
        return new JAXBElement<ResultRowType>(_ResultRow_QNAME, ResultRowType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResultColumnType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://wse.vlaanderen.be/BeschikbareEntitlementArtefactService/common/DataTypes/v100", name = "Artefact")
    public JAXBElement<ResultColumnType> createArtefact(ResultColumnType value) {
        return new JAXBElement<ResultColumnType>(_Artefact_QNAME, ResultColumnType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WhereFilterType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://wse.vlaanderen.be/BeschikbareEntitlementArtefactService/common/DataTypes/v100", name = "SingleWhereFilterQuery")
    public JAXBElement<WhereFilterType> createSingleWhereFilterQuery(WhereFilterType value) {
        return new JAXBElement<WhereFilterType>(_SingleWhereFilterQuery_QNAME, WhereFilterType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WhereQueryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://wse.vlaanderen.be/BeschikbareEntitlementArtefactService/common/DataTypes/v100", name = "WhereQuery")
    public JAXBElement<WhereQueryType> createWhereQuery(WhereQueryType value) {
        return new JAXBElement<WhereQueryType>(_WhereQuery_QNAME, WhereQueryType.class, null, value);
    }

}
