//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.27 at 06:33:24 PM IST 
//


package it.geosolutions.geostore.soap.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://wse.vlaanderen.be/BeschikbareEntitlementArtefactService/common/DataTypes/v100}WhereQueryList"/&gt;
 *         &lt;element ref="{http://wse.vlaanderen.be/BeschikbareEntitlementArtefactService/common/DataTypes/v100}SelectAttributeList"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "whereQueryList",
    "selectAttributeList"
})
@XmlRootElement(name = "QuerySingleFilterBeschikbareEntitlementRequest")
public class QuerySingleFilterBeschikbareEntitlementRequest {

    @XmlElement(name = "WhereQueryList", required = true)
    protected WhereQueryListType whereQueryList;
    @XmlElement(name = "SelectAttributeList", required = true)
    protected SelectAttributeListType selectAttributeList;

    /**
     * Gets the value of the whereQueryList property.
     * 
     * @return
     *     possible object is
     *     {@link WhereQueryListType }
     *     
     */
    public WhereQueryListType getWhereQueryList() {
        return whereQueryList;
    }

    /**
     * Sets the value of the whereQueryList property.
     * 
     * @param value
     *     allowed object is
     *     {@link WhereQueryListType }
     *     
     */
    public void setWhereQueryList(WhereQueryListType value) {
        this.whereQueryList = value;
    }

    /**
     * Gets the value of the selectAttributeList property.
     * 
     * @return
     *     possible object is
     *     {@link SelectAttributeListType }
     *     
     */
    public SelectAttributeListType getSelectAttributeList() {
        return selectAttributeList;
    }

    /**
     * Sets the value of the selectAttributeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SelectAttributeListType }
     *     
     */
    public void setSelectAttributeList(SelectAttributeListType value) {
        this.selectAttributeList = value;
    }

}
