//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.27 at 06:33:24 PM IST 
//


package it.geosolutions.geostore.soap.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QueryResultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QueryResultType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://wse.vlaanderen.be/BeschikbareEntitlementArtefactService/common/DataTypes/v100}SingleWhereFilterQuery"/&gt;
 *         &lt;element ref="{http://wse.vlaanderen.be/BeschikbareEntitlementArtefactService/common/DataTypes/v100}QueryResultSet"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QueryResultType", propOrder = {
    "singleWhereFilterQuery",
    "queryResultSet"
})
public class QueryResultType {

    @XmlElement(name = "SingleWhereFilterQuery", required = true)
    protected WhereFilterType singleWhereFilterQuery;
    @XmlElement(name = "QueryResultSet", required = true)
    protected QueryResultSetType queryResultSet;

    /**
     * Gets the value of the singleWhereFilterQuery property.
     * 
     * @return
     *     possible object is
     *     {@link WhereFilterType }
     *     
     */
    public WhereFilterType getSingleWhereFilterQuery() {
        return singleWhereFilterQuery;
    }

    /**
     * Sets the value of the singleWhereFilterQuery property.
     * 
     * @param value
     *     allowed object is
     *     {@link WhereFilterType }
     *     
     */
    public void setSingleWhereFilterQuery(WhereFilterType value) {
        this.singleWhereFilterQuery = value;
    }

    /**
     * The resultset for the Query
     * 
     * @return
     *     possible object is
     *     {@link QueryResultSetType }
     *     
     */
    public QueryResultSetType getQueryResultSet() {
        return queryResultSet;
    }

    /**
     * Sets the value of the queryResultSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryResultSetType }
     *     
     */
    public void setQueryResultSet(QueryResultSetType value) {
        this.queryResultSet = value;
    }

}
