//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.27 at 06:33:24 PM IST 
//


package it.geosolutions.geostore.soap.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResultColumnType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResultColumnType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ArtefactValue" type="{http://wse.vlaanderen.be/BeschikbareEntitlementArtefactService/common/DataTypes/v100}ArtefactValueType"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="ArtefactName" use="required" type="{http://wse.vlaanderen.be/BeschikbareEntitlementArtefactService/common/DataTypes/v100}ArtefactNameType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResultColumnType", propOrder = {
    "artefactValue"
})
public class ResultColumnType {

    @XmlElement(name = "ArtefactValue", required = true)
    protected String artefactValue;
    @XmlAttribute(name = "ArtefactName", required = true)
    protected String artefactName;

    /**
     * Gets the value of the artefactValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArtefactValue() {
        return artefactValue;
    }

    /**
     * Sets the value of the artefactValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArtefactValue(String value) {
        this.artefactValue = value;
    }

    /**
     * Gets the value of the artefactName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArtefactName() {
        return artefactName;
    }

    /**
     * Sets the value of the artefactName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArtefactName(String value) {
        this.artefactName = value;
    }

}
